APPOINTMENT_TYPES = [
    'Joints pain',
    'Baldness',
    'Migraine',
    'Obesity',
    'Piles',
    'Infertility',
    'Sexual Problem',
    'Psoriasis',
    'High BP',
    'High Cholesterol',
    'Breathing Difficulty',
    'Hyperacidity',
    'Hepatitis B&C',
    'Skin Disorder',
    'Diabetes',
    'Paralysis',
    'Depression',
    'Cervical Spondylitis',
    'Gynaecology Problems'
]
